@startuml
[*] --> PedidoPendiente

PedidoPendiente --> PedidoAprobado : pagar() [saldo >= total]
PedidoPendiente --> PedidoRechazado : pagar() [saldo < total]

PedidoAprobado --> [*] : enviar()
PedidoRechazado --> [*]
@enduml
