@startuml
[*] --> Pedido

state Pedido {
  [*] --> Preparando
  Preparando --> Empaquetando : listo()
  Empaquetando --> Enviado    : enviar()
  Enviado --> [*]
}

Pedido --> [*] : entregar()
@enduml
