@startuml
[*] --> Pedido

state Pedido {
  --
  state Pago {
    [*] --> PendientePago
    PendientePago --> Confirmado : pagar()
  }
  --
  state Envío {
    [*] --> Preparando
    Preparando --> Enviado : enviar()
  }
}

Pedido --> [*] : finalizar()
@enduml
