@startuml
title Diagrama de Timing – Ciclo de Vida del Usuario

robust "Usuario" as U

@0
U is NoRegistrado

@1
U is Registrado : Registrarse

@2
U is Activo : Verificación completada

@3
U is Bloqueado : Bloqueado por gestor

@4
U is Activo : Desbloqueado

@5
U is Eliminado : Eliminar cuenta


@enduml

