@startuml
title Diagrama de Timing – Ciclo de Vida del Usuario

robust "Usuario" as U

@0
U is NoRegistrado

@1
U is Registrado : Registrarse

@+2
U is Activo : Verificación completada

@+2
U is Bloqueado : Bloqueado por gestor

@+1
U is Activo : Desbloqueado

@+1
U is Eliminado : Eliminar cuenta


@enduml

