@startuml
abstract class Persona {
  - id: int
  + dni: String
  # nombre: String
  ~ edad: int
  {static} contador: int

  + getId(): int
  + setId(id: int): void
  {abstract} getDescripcion(): String
}
@enduml

