@startuml
object cliente1 {
  id = 102
  nombre = "Ana López"
  email = "ana@example.com"
}

object pedido1 {
  id = 101
  fecha = "2025-09-28"
  total = 250.00
  cliente_id = 102
}

cliente1 -- pedido1
@enduml
